# Generated by Django 4.0.5 on 2022-06-19 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SNUsers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SNPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_text', models.CharField(max_length=100, null=True)),
                ('time', models.CharField(default='06/19/2022 09:32:42 PM', max_length=50)),
                ('comment', models.CharField(max_length=100, null=True)),
                ('like', models.ManyToManyField(related_name='liked_users', to='SNUsers.snuser')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SNUsers.snuser')),
            ],
        ),
    ]
