# Generated by Django 4.0.5 on 2022-06-19 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_alter_snpost_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='snpost',
            name='reply',
            field=models.ManyToManyField(to='Posts.snpost'),
        ),
        migrations.AlterField(
            model_name='snpost',
            name='time',
            field=models.CharField(default='06/20/2022 03:56:53 AM', max_length=50),
        ),
    ]
