# Generated by Django 4.0.5 on 2022-06-19 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SNUsers', '0002_alter_snuser_modified_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snuser',
            name='modified_time',
            field=models.CharField(default='06/20/2022 03:56:53 AM', max_length=50),
        ),
    ]
